version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: 4sync
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: xpto
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
