
DROP TABLE IF EXISTS public.phone;

CREATE TABLE public.phone (
  id uuid NOT NULL,
  zone varchar NOT NULL,
  code varchar NOT NULL,
  phone varchar NOT NULL,
  CONSTRAINT phone_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.address;

CREATE TABLE public.address (
  id uuid NOT NULL,
  street varchar NOT NULL,
  number varchar NOT NULL,
  zip_code varchar NOT NULL,
  CONSTRAINT address_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.contact;

CREATE TABLE public.contact (
  id uuid NOT NULL,
  address_id uuid NOT NULL,
  name varchar NOT NULL,

  CONSTRAINT contact_pk PRIMARY KEY (id),
  CONSTRAINT address_fk FOREIGN KEY (address_id) REFERENCES public.address(id)
);

CREATE TABLE public.contact_phone (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  phone_id uuid NOT NULL,
  contact_id uuid NOT NULL,

  CONSTRAINT contact_phone_pk PRIMARY KEY (id),
  CONSTRAINT phone_fk FOREIGN KEY (phone_id) REFERENCES public.phone(id),
  CONSTRAINT contact_fk FOREIGN KEY (contact_id) REFERENCES public.contact(id)
);
